### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by knkrth** [sirhypernova/c9launcher#3]
Hi, While installing the node packages I got the following errors,

```
c9launcher$ npm i
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> sqlite3@3.1.13 install /home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
make: Entering directory '/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VXPrintf’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25065:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         flag_long = sizeof(char*)==sizeof(long int);
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25067:7: note: here
       case etORDINAL:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VXPrintf’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25065:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         flag_long = sizeof(char*)==sizeof(long int);
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:25067:7: note: here
       case etORDINAL:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GetToken’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GetToken’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137154:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( !sqlite3Isdigit(z[1]) )
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137163:5: note: here
     case CC_DIGIT: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137154:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( !sqlite3Isdigit(z[1]) )
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137163:5: note: here
     case CC_DIGIT: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137253:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( z[1]=='\'' ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137253:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( z[1]=='\'' ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137267:5: note: here
     case CC_ID: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:137267:5: note: here
     case CC_ID: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3ExprCodeTarget’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93034:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case TK_AGG_COLUMN: {
                         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3ExprCodeTarget’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93047:5: note: here
     case TK_COLUMN: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93034:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case TK_AGG_COLUMN: {
                         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:93047:5: note: here
     case TK_COLUMN: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘resolveP2Values’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71026:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
           if( pOp->p2!=0 ) p->readOnly = 0;
             ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘resolveP2Values’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71026:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
           if( pOp->p2!=0 ) p->readOnly = 0;
             ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71029:9: note: here
         case OP_AutoCommit:
         ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:71029:9: note: here
         case OP_AutoCommit:
         ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fkActionTrigger’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fkActionTrigger’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107247:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if( !pChanges ){
           ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107247:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if( !pChanges ){
           ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107251:7: note: here
       default:
       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:107251:7: note: here
       default:
       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GenerateConstraintChecks’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108736:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
         onError = OE_Abort;
                 ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3GenerateConstraintChecks’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108736:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
         onError = OE_Abort;
                 ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108739:7: note: here
       case OE_Rollback:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:108739:7: note: here
       case OE_Rollback:
       ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78202:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( (pIn3->flags & MEM_Null)==0 ) break;
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘sqlite3VdbeExec’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78202:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( (pIn3->flags & MEM_Null)==0 ) break;
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78236:1: note: here
 case OP_Halt: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78367:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( pOp->p1>db->aLimit[SQLITE_LIMIT_LENGTH] ){
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78236:1: note: here
 case OP_Halt: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78367:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if( pOp->p1>db->aLimit[SQLITE_LIMIT_LENGTH] ){
     ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78386:1: note: here
 case OP_String: {          /* out2 */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78386:1: note: here
 case OP_String: {          /* out2 */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78941:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_Function;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78944:1: note: here
 case OP_Function: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78941:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_Function;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:78944:1: note: here
 case OP_Function: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82140:38: warning: this statement may fall through [-Wimplicit-fallthrough=]
   p->aCounter[SQLITE_STMTSTATUS_SORT]++;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82140:38: warning: this statement may fall through [-Wimplicit-fallthrough=]
   p->aCounter[SQLITE_STMTSTATUS_SORT]++;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82155:1: note: here
 case OP_Rewind: {        /* jump */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83361:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_AggStep;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:82155:1: note: here
 case OP_Rewind: {        /* jump */
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83364:1: note: here
 case OP_AggStep: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83361:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   pOp->opcode = OP_AggStep;
               ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:83364:1: note: here
 case OP_AggStep: {
 ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fts3SnippetFunc’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘fts3SnippetFunc’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146657:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 6: nToken = sqlite3_value_int(apVal[5]);
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:5: note: here
     case 5: iCol = sqlite3_value_int(apVal[4]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146657:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 6: nToken = sqlite3_value_int(apVal[5]);
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:5: note: here
     case 5: iCol = sqlite3_value_int(apVal[4]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 5: iCol = sqlite3_value_int(apVal[4]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146658:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 5: iCol = sqlite3_value_int(apVal[4]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:5: note: here
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:5: note: here
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146659:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 4: zEllipsis = (const char*)sqlite3_value_text(apVal[3]);
             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:5: note: here
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:5: note: here
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146660:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
     case 3: zEnd = (const char*)sqlite3_value_text(apVal[2]);
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146661:5: note: here
     case 2: zStart = (const char*)sqlite3_value_text(apVal[1]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:146661:5: note: here
     case 2: zStart = (const char*)sqlite3_value_text(apVal[1]);
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘rtreeNonleafConstraint’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162310:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162310:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->op!=RTREE_EQ ) break;  /* RTREE_LE and RTREE_LT end here */
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162313:5: note: here
     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */
     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:162313:5: note: here
     default: /* RTREE_GT or RTREE_GE,  or fallthrough of RTREE_EQ */
     ^~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonRenderNode’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonRenderNode’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176768:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( pNode->jnFlags & JNODE_RAW ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176768:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( pNode->jnFlags & JNODE_RAW ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176774:5: note: here
     case JSON_REAL:
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonReturn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176774:5: note: here
     case JSON_REAL:
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonReturn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176891:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       int_as_real: /* fall through to real */;
       ^~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176891:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       int_as_real: /* fall through to real */;
       ^~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176893:5: note: here
     case JSON_REAL: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonEachColumn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:176893:5: note: here
     case JSON_REAL: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘jsonEachColumn’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178258:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->bRecursive ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178258:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if( p->bRecursive ){
         ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178268:5: note: here
     case JEACH_ROOT: {
     ^~~~
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:178268:5: note: here
     case JEACH_ROOT: {
     ^~~~
sed: can't read ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw: No such file or directory
  AR(target) Release/obj.target/deps/sqlite3.a
rm: cannot remove './Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw': No such file or directory
deps/sqlite3.target.mk:129: recipe for target 'Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1
make: Leaving directory '/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1040-gcp
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-1040-gcp
node-pre-gyp ERR! command "/usr/bin/node" "/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:0:
../src/database.h:10:10: fatal error: nan.h: No such file or directory
 #include <nan.h>
          ^~~~~~~
compilation terminated.
node_sqlite3.target.mk:121: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory '/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1040-gcp
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home//workspace/c9launcher/node_modules/sqlite3po/node_modules/sqlite3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN c9launcher@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home//.npm/_logs/2019-09-02T07_27_53_828Z-debug.log
```

Development Environment 
```
node v10.16.3
npm 6.9.0
```

**Comment by sirhypernova** [comment]
Huh, that's strange. I've only tested this on Node v8, and that was ages
ago. As for the moved names, that's just because I haven't updated it in so
long.

I'm probably going to archive this repo, since it isn't really production
ready, and I don't have any intention of finishing it at this point in time.

I may do a full rewrite in the future.

**Comment by knkrth** [comment]
Ok, Thanks for this project. I'll try to run it on node v8

**Comment by knkrth** [comment]
```"sqlite3po": "^1.5.0"``` package is causing the error.

**Comment by knkrth** [comment]
Broken package has been fixed by [sqlite3po](https://github.com/frenya/sqlite3po) update the package on your project.
