### ISSUE TITLE
Error in npm Start

### ISSUE THREAD

**Issue by Muhamadrianto97** [sirhypernova/c9launcher#7]
how To fix this?
i want run npm start but got this error
![Capture2](https://user-images.githubusercontent.com/25837733/65553914-3ae66200-df52-11e9-921b-c8ee97434a3e.PNG)

> c9launcher@1.0.0 start /root/c9launcher
> NODE_ENV=production node index.js

/root/c9launcher/index.js:17
database.then(async db => {
                    ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! c9launcher@1.0.0 start: `NODE_ENV=production node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the c9launcher@1.0.0 start script.
npm ERR! This is most likely a problem with the c9launcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls c9launcher
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.19.34-11.al7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root/c9launcher
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/c9launcher/npm-debug.log
npm ERR! not ok code 0

**Comment by sirhypernova** [comment]
Hello! Please update your nodejs version to at least Node 8. You are on
v0.10.30, which is too old for this.

**Comment by Muhamadrianto97** [comment]
I have updated it but still get an error but it's different
how to fix this?

> c9launcher@1.0.0 start /root/c9launcher
> NODE_ENV=production node index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'connect-sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/c9launcher/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! c9launcher@1.0.0 start: `NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the c9launcher@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-24T23_13_53_416Z-debug.log

**Comment by Muhamadrianto97** [comment]
thanks worked
